name: Terraform ec2 creation
on: workflow_dispatch
jobs:
    create-runner:
        runs-on: ubuntu-latest
        steps:
          - name: check out the repo code
            uses: actions/checkout@v6

          - name: list files
            run: ls -l



